name: look_up
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  # firebase_core: ^0.3.0
  cloud_firestore: ^0.16.0 # cloud_firestore: ^0.9.7+2
  image_picker: ^0.6.7+21 # image_picker: ^0.6.0+2
  firebase_storage: ^7.0.0 # firebase_storage: ^2.1.0+1
  # firebase_auth: ^0.8.3
  google_sign_in: ^4.5.9 # google_sign_in: ^4.0.1+1
  geolocator: ^6.1.13 # geolocator: 5.0.1
  geocoding: ^1.0.5
  uuid: ^2.2.2 # uuid: ^2.0.0
  image: ^2.1.19 # image: ^2.0.7
  animator: ^2.0.2 # animator: 0.1.4
  # cupertino_icons: ^0.1.2
  path_provider: ^1.6.27 # path_provider: ^0.5.0+1
  # firebase_messaging: ^4.0.0+1
  timeago: ^2.0.29
  cached_network_image: # cached_network_image:
  flutter_svg:



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
